#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
. "$(dirname -- "$0")/utils.sh"

print_message "🔎 Check if the commit message matches the pattern of conventional commits"
npx --no -- commitlint --edit ${1}