name: Publish ui and package

on:
  release:
    types: [created]
  workflow_dispatch: # Allows manual trigger

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build UI
        run: pnpm run build:ui

      - name: Deploy UI
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Build package
        run: pnpm run build:package

      - name: Publish package
        run: npm pkg delete scripts.prepare && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
